# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkiliAgent < Formula
  desc "Agent for Akili, the security-first control plane for autonomous AI operator agents"
  homepage "https://goakili.dev"
  version "0.3.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goakili/akili/releases/download/v0.3.0/akili-agent_0.3.0_darwin_amd64.tar.gz"
      sha256 "f890ac3928655c9cf06d733350e08f33b67febcd60a49339f38b577b221da7d5"

      define_method(:install) do
        bin.install "akili-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goakili/akili/releases/download/v0.3.0/akili-agent_0.3.0_darwin_arm64.tar.gz"
      sha256 "57da141b560cc45f3a64ee99981004f2326ddfa3952a014418e15b2e686f6d7a"

      define_method(:install) do
        bin.install "akili-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goakili/akili/releases/download/v0.3.0/akili-agent_0.3.0_linux_amd64.tar.gz"
      sha256 "ac7d15b25284905d5236b5ebc1d172464133090d1ccdddd65709516ddffafbb8"
      define_method(:install) do
        bin.install "akili-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goakili/akili/releases/download/v0.3.0/akili-agent_0.3.0_linux_arm64.tar.gz"
      sha256 "0143c2414a9f56465fc724534fcc61f698a866ab8f36b80d385b7c4ef9fd99d9"
      define_method(:install) do
        bin.install "akili-agent"
      end
    end
  end

  def post_install
    (var/"akili-agent").mkpath
    (var/"log").mkpath
  end

  def caveats
    <<~EOS
      Enroll the agent once with the join token from your control plane (Agents → Add agent):

        AKILI_JOIN_TOKEN=akj_... akili-agent enroll --url https://akili.example.com --state-dir #{var}/akili-agent

      Then start it in the background, now and at login:

        brew services start akili-agent

      Logs: #{var}/log/akili-agent.log
    EOS
  end

  service do
    run [opt_bin/"akili-agent", "start", "--state-dir", var/"akili-agent"]
    keep_alive true
    log_path var/"log/akili-agent.log"
    error_log_path var/"log/akili-agent.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/akili-agent version")
  end
end
