# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkiliAgent < Formula
  desc "Agent for Akili, the security-first control plane for autonomous AI operator agents"
  homepage "https://goakili.dev"
  version "0.1.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goakili/akili/releases/download/v0.1.0/akili-agent_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1586b5030ceabe6f585b36d41029d7197376ae85c0b844cbce1d3bf3e8e7d47"

      define_method(:install) do
        bin.install "akili-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goakili/akili/releases/download/v0.1.0/akili-agent_0.1.0_darwin_arm64.tar.gz"
      sha256 "eef964b873fc8c95dfaf66876426b6b01e7ff59c8b991c59643657cfce410a94"

      define_method(:install) do
        bin.install "akili-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goakili/akili/releases/download/v0.1.0/akili-agent_0.1.0_linux_amd64.tar.gz"
      sha256 "a49a5bd44e53a95f9048dee6705ac0fa242191dced83ba07a262cfa113aa1a13"
      define_method(:install) do
        bin.install "akili-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goakili/akili/releases/download/v0.1.0/akili-agent_0.1.0_linux_arm64.tar.gz"
      sha256 "9808e0a14a2a0e11f675969e68b1d2b8193a42b54a4c335e2f021cc3e64f8717"
      define_method(:install) do
        bin.install "akili-agent"
      end
    end
  end

  def post_install
    (var/"akili-agent").mkpath
    (var/"log").mkpath
  end

  def caveats
    <<~EOS
      Enroll the agent once with the join token from your control plane (Agents → Add agent):

        AKILI_JOIN_TOKEN=akj_... akili-agent enroll --url https://akili.example.com --state-dir #{var}/akili-agent

      Then start it in the background, now and at login:

        brew services start akili-agent

      Logs: #{var}/log/akili-agent.log
    EOS
  end

  service do
    run [opt_bin/"akili-agent", "start", "--state-dir", var/"akili-agent"]
    keep_alive true
    log_path var/"log/akili-agent.log"
    error_log_path var/"log/akili-agent.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/akili-agent version")
  end
end
