# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AkiliAgent < Formula
  desc "Agent for Akili, the security-first control plane for autonomous AI operator agents"
  homepage "https://goakili.dev"
  version "0.0.2"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goakili/akili/releases/download/v0.0.2/akili-agent_0.0.2_darwin_amd64.tar.gz"
      sha256 "13b44c3a3d12a4513831e74078182e76715c322fcf84f15400be2d30b37f425b"

      define_method(:install) do
        bin.install "akili-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goakili/akili/releases/download/v0.0.2/akili-agent_0.0.2_darwin_arm64.tar.gz"
      sha256 "f233319e8db10e5661e3ecff0102d7f6aed349bfb88c4e110c04c4bb66f40fa3"

      define_method(:install) do
        bin.install "akili-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goakili/akili/releases/download/v0.0.2/akili-agent_0.0.2_linux_amd64.tar.gz"
      sha256 "1b6fe23eca4f03f6b57f1a4f71660a0d449be54f04a8df307e63a16563dc17c3"
      define_method(:install) do
        bin.install "akili-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goakili/akili/releases/download/v0.0.2/akili-agent_0.0.2_linux_arm64.tar.gz"
      sha256 "b5adf93285932d2eaef67162727ad7eeb16ca3f9a5ab1642ff8c99e6186fcd30"
      define_method(:install) do
        bin.install "akili-agent"
      end
    end
  end

  def post_install
    (var/"akili-agent").mkpath
    (var/"log").mkpath
  end

  def caveats
    <<~EOS
      Enroll the agent once with the join token from your control plane (Agents → Add agent):

        AKILI_JOIN_TOKEN=akj_... akili-agent enroll --url https://akili.example.com --state-dir #{var}/akili-agent

      Then start it in the background, now and at login:

        brew services start akili-agent

      Logs: #{var}/log/akili-agent.log
    EOS
  end

  service do
    run [opt_bin/"akili-agent", "run", "--state-dir", var/"akili-agent"]
    keep_alive true
    log_path var/"log/akili-agent.log"
    error_log_path var/"log/akili-agent.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/akili-agent version")
  end
end
